### ISSUE TITLE
Pad preview document body instead of iframe element

### ISSUE THREAD

**Issue by rbardini** [rbardini/storybook-addon-paddings#1]
In order to better support Storybook's new [`layout` parameter](https://github.com/storybookjs/storybook/pull/9229), the addon should add paddings to the preview document body instead of the iframe element.

**Comment by KevinVandy** [comment]
I second this. I was excited when I saw this addon thinking that it would just create a div around the story and give that padding. I was disappointed when I saw that this is wrapping the entire canvas iframe in a div to give that padding. The way it is currently implemented is not very useful. It's acting more like the viewport addon. None of my components hover effects (tooltips) will show over the space created by the padding since it is in iframe.
